name: Run Python Script

on:
  schedule:
    #- cron: '5 */3 * * *'
    - cron: '0 17,1,9 * * *'
  workflow_dispatch:

jobs:
  sync_live_list:
    runs-on: ubuntu-latest

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Run Python Script
      run: |
          cd Tv_search
          python search_Tv.py
